### ISSUE TITLE
Loss2 = 0

### ISSUE THREAD

**Issue by anhdtd-vbee** [Dingseewhole/CI_LightGCN_master#1]
Hello, I just read your paper and your code in this repository. when i re-ran the code the result is same as the paper but I found that  "loss2" in get_our_loss function is always equal to 0, and it wasn't calculated like equation (10) in the paper. Moreover, in your code, it only apply equation (9) for only user nodes instead of both user and item nodes while making predictions.  Can you explain why this happens. Thanks in advance.

**Comment by Dingseewhole** [comment]
1. If you run the codes for quickly reproducing, it means just using the CED operator in the inference phase by the Eq (9). So the model parameters are not updated when you run the code, thus the loss2 equals 0.
2. In our implementation, we only apply CED on user nodes. And experimental results in the paper show that only applying CED to the user node can boost the performance. Since users and item nodes have equivalent positions[1] in the bipartite graph, you can also try to apply CED on both user and item nodes to pursue higher performance improvement. 

[1] WSDM 2021 Leave No User Behind: Towards Improving the Utility of Recommender Systems for Non-mainstream Users

**Comment by Dingseewhole** [comment]
We have already tuned the block of code. The corresponding negative items are the same as the anchor item, so the loss2 does not always equal 0. To achieve the best performance, you can fine-tune the hyperparameter world.radio_loss to control the impact of loss2, and set world.radio_loss=0 can make the .loss2 == 0
